"use client";
import { useState } from "react";
import { submitTodayResult } from "@/actions/v3";
import { createClient } from "@/lib/supabase/client";

export function ResultComposer({ dailyMomentId }:{dailyMomentId:string}){
 const [type,setType]=useState<"text"|"choice"|"photo">("text"); const [text,setText]=useState(""); const [choice,setChoice]=useState(""); const [why,setWhy]=useState(""); const [media,setMedia]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function upload(file:File){setBusy(true);setMessage("");const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user){setMessage("Please log in again.");setBusy(false);return} if(!file.type.startsWith("image/")||file.size>8*1024*1024){setMessage("Use an image up to 8MB.");setBusy(false);return} const path=`${user.id}/v3/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"")}`;const {error}=await sb.storage.from("moment-media").upload(path,file,{contentType:file.type,upsert:false});if(error){setMessage(error.message);setBusy(false);return}setMedia(sb.storage.from("moment-media").getPublicUrl(path).data.publicUrl);setBusy(false)}
 async function submit(){setBusy(true);setMessage("");const fd=new FormData();fd.set("dailyMomentId",dailyMomentId);fd.set("resultType",type);fd.set("textContent",text);fd.set("choiceValue",choice);fd.set("why",why);fd.set("mediaUrl",media);const r=await submitTodayResult(fd);setMessage(r.success?"YOUR MOMENT IS MADE.":r.error);setBusy(false)}
 return <div className="rounded-[28px] border border-[#ded8ce] bg-white/70 p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[#ef6b35]">Your answer</p><div className="mt-4 flex gap-2">{(["text","choice","photo"] as const).map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-full border px-4 py-2 text-xs font-black ${type===x?"border-[#171614] bg-[#171614] text-white":"border-[#ded8ce] bg-white"}`}>{x}</button>)}</div>{type==="text"&&<textarea value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="What did you find?" className="mt-4 min-h-32 w-full rounded-2xl border border-[#ded8ce] bg-white p-4 outline-none"/>}{type==="choice"&&<div className="mt-4 grid grid-cols-2 gap-2">{["Something ordinary","Something surprising","Something beautiful","Something strange"].map(x=><button key={x} onClick={()=>setChoice(x)} className={`rounded-2xl border p-4 text-left text-sm font-bold ${choice===x?"border-[#171614] bg-[#f1ece3]":"border-[#ded8ce] bg-white"}`}>{x}</button>)}</div>}{type==="photo"&&<div className="mt-4"><label className="flex cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-[#cfc7bb] p-8 text-sm font-bold">{media?"Photo ready — choose another":"Bring back a photo"}<input type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></div>}<input value={why} onChange={e=>setWhy(e.target.value)} maxLength={500} placeholder="Optional: why this one?" className="mt-3 w-full rounded-2xl border border-[#ded8ce] bg-white p-4 outline-none"/><button onClick={()=>void submit()} disabled={busy || (type==="text"?!text.trim():type==="choice"?!choice:!media)} className="mt-4 w-full rounded-2xl bg-[#171614] px-5 py-4 text-sm font-black text-white disabled:opacity-40">{busy?"BRINGING IT BACK…":"BRING IT BACK"}</button>{message&&<p role="status" className="mt-3 text-sm font-bold">{message}</p>}</div>
}
